title: Yacine | Développeur Web
email: benbrikyacine60@gmail.com
description: "Étudiant à la WebAcademie par Epitech. Passionné par le développement web et la performance."
baseurl: "/Markdown-P"
url: "https://yacineb03.github.io"


remote_theme: mmistakes/minimal-mistakes
minimal_mistakes_skin: "dark"


author:
  name: "Yacine Benbrik"
  avatar: "/assets/images/profil-accuel.jpg"
  bio: "Étudiant WebAcademie @ Epitech"
  location: "Marseille, France"
  links:
    - label: "GitHub"
      url: "https://github.com/yacineb03"
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/yacine-benbrik-90385a33a/"

footer:
  links:
    - label: "LinkedIn"
      url: "https://www.linkedin.com/in/yacine-benbrik-90385a33a/"
    - label: "GitHub"
      url: "https://github.com/yacineb03"
    - label: "Projets"
      url: "/projects/"
    - label: "Contact"
      url: "/contact/"
    - label: "À propos"
      url: "/about/"

atom_feed:
  hide: true
show_downloads: false
show_date: false
words_per_minute: 200

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
      share: false
      related: false
      comments: false
      read_time: false
      show_date: false
  - scope:
      path: ""
      type: projects
    values:
      layout: single
      author_profile: true
      read_time: false
      show_date: false

collections:
  projects:
    output: true
    permalink: /projects/:path/

plugins:
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
